-- ==============================================================================
-- SALON EMİN — Supabase "randevular" Tablosu ve Gerçek Zamanlı Slot Kilitleme
-- ==============================================================================
-- Bu SQL kodunu Supabase Dashboard -> SQL Editor alanına yapıştırıp "Run" butonuna basarak
-- saniyeler içinde veritabanı tablosunu, kısıtlamalarını ve Realtime ayarlarını kurabilirsiniz.

-- 1. "randevular" Tablosunun Oluşturulması
create table if not exists public.randevular (
  id bigint generated by default as identity primary key,
  berber_adi text not null,          -- "Ahmet Usta", "Mehmet Usta", vb.
  tarih text not null,               -- YYYY-MM-DD formatında tarih (Örn: "2026-10-10")
  saat text not null,                -- 30 dk aralıklı saat dilimi (Örn: "14:30")
  musteri_adi text not null,         -- Müşterinin Adı Soyadı
  telefon text not null,             -- Müşterinin Telefon Numarası
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Aynı berber, aynı gün ve aynı saat için çifte rezervasyonu veritabanı seviyesinde önleme:
  constraint unique_berber_tarih_saat unique (berber_adi, tarih, saat)
);

-- 2. Hızlı Sorgulama İçin İndeksler
create index if not exists idx_randevular_berber_tarih on public.randevular (berber_adi, tarih);
create index if not exists idx_randevular_tarih on public.randevular (tarih);

-- 3. Supabase Realtime (Gerçek Zamanlı Yayın) Özelliğini Aktif Etme
-- Bu sayede bir kullanıcı randevu aldığında diğer kullanıcıların ekranında saat anında kilitlenir.
alter publication supabase_realtime add table public.randevular;

-- 4. Row Level Security (RLS) Politikaları
-- Web sitesi ziyaretçilerinin uygun saatleri sorgulayabilmesi ve randevu kaydedebilmesi için:
alter table public.randevular enable row level security;

-- Herkes mevcut randevuları (saat müsaitliğini kontrol etmek için) okuyabilir:
drop policy if exists "Randevular herkes tarafından okunabilir" on public.randevular;
create policy "Randevular herkes tarafından okunabilir"
  on public.randevular for select
  using (true);

-- Herkes yeni randevu ekleyebilir:
drop policy if exists "Randevular herkes tarafından eklenebilir" on public.randevular;
create policy "Randevular herkes tarafından eklenebilir"
  on public.randevular for insert
  with check (true);

-- 5. Başlangıç / Demo Kaydı (Opsiyonel Örnek):
-- insert into public.randevular (berber_adi, tarih, saat, musteri_adi, telefon)
-- values ('Ahmet Usta', to_char(now(), 'YYYY-MM-DD'), '11:00', 'Örnek Müşteri', '05526699597');
